---

namespace: 'niceshops'
name: 'mssql'
version: 1.0.0
readme: 'README.md'
authors:
  - 'Rene Rath <rene.rath@niceshops.com>'
description: "Ansible-Role and Notes to run MSSQL on Linux"
license_file: 'LICENSE.txt'
tags:
  - 'database'
  - 'windows'
  - 'microsoft'
  - 'sqlserver'
  - 'db'
  - 'ssis'
dependencies: {}
repository: 'https://github.com/niceshops/mssql-linux'
documentation: 'https://github.com/niceshops/mssql-linux/blob/main/README.md'
homepage: 'https://www.niceshops.com'
issues: 'https://github.com/niceshops/mssql-linux/issues'
build_ignore: []
